# Generated by Django 3.1 on 2021-07-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20210710_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='image_field',
        ),
    ]
