# Generated by Django 3.1 on 2021-07-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_auto_20210710_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image_field',
            new_name='profile_pic',
        ),
    ]
